### ISSUE TITLE
Error when making API calls

### ISSUE THREAD

**Issue by ssempervirens** [openstates/pyopenstates#14]
When I try to use the pyopenstates API, I get an API error: `"error": "quota exceeded: 0/day", "note": "Please consider moving to API v2 or v3.  API v1 will be removed in 2021."`

My pyopenstates version is up to date with version 1.2.0

It looks like pyopenstates has not been updated since 2018, so I just want to confirm that this error is entirely because the API has not been updated, and that pyopenstates is not usable until the package is updated to the v2 or v3 API. Issue #13 mentions a potential update to v3 it'd also be great to be able to confirm whether this package is under active development, or will not be maintained going forward. 

Thanks!

**Comment by jamesturk** [comment]
there is a key set in the secrets that you can access like this:

https://github.com/openstates/pyopenstates/blob/main/.github/workflows/main.yml#L28

**Comment by ssempervirens** [comment]
It looks like the yml file is correct, but the reason the tests can't run is that my fork can't access the secret API key. I think you either have to merge this, and I can fix any issues, or give me commit access to the repo so that I can make commits to the repo rather than my fork.
