### ISSUE TITLE
Consider migrating from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by ssempervirens** [openstates/pyopenstates#16]
Travis CI was bought by Idera some time ago, and immediately laid off half of its engineers -- my understanding is that Idera is a private equity firm that is well known for acquiring companies and essentially stripping them for parts. Travis isn't really being developed anymore.

I would suggest github actions as an alternative, which has better performance and better integration with github.

If you're okay with this @jamesturk, I'm happy to open a PR with this change.

**Comment by jamesturk** [comment]
That’d be great, I hadn’t had a chance to look at the PR yet but saw the note and was going to investigate the same.

The rest of the repos here have migrated already if it’s any help to look at them.

Thanks again!!

**Comment by jamesturk** [comment]
this is semi-working, but the current tests fail as they're against v1.  thanks for this!
