### ISSUE TITLE
API Key Problem

### ISSUE THREAD

**Issue by dwlarson10** [openstates/pyopenstates#9]
I am working with the pyopenstates package and I am having a hard time setting up the apikey. When I attempt to use this function pyopenstates.set_api_key(apikey) I get an error saying “‘str’ object is not callable” and when I try to set the environment variable OPENSTATES_API_KEY I still get an error saying that there is no API key. Can you help?

I using a anacanda python 2.7 set up with a jupyter notebook. I was assuming I could just use this set_api_key([my_apikey]).

**Comment by thatipelli69** [comment]
Is this code for openstates v2 api?

**Comment by seanthegeek** [comment]
@thatipelli69 v1

**Comment by thatipelli69** [comment]
Thank you for your response

**Comment by thatipelli69** [comment]
Do we have any library for v2 also?

I need to update existing web app to use v2 services.

**Comment by seanthegeek** [comment]
I didn't even know v2 existed. I'll add it to my to do list.
